sudo: false

language: php

php:
  - 7.2
  - 7.3
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: master

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=tests/cover

cache:
  directories:
    - $HOME/.composer/cache